### ISSUE TITLE
how can i run this project on my system,i dont know java?

### ISSUE THREAD

**Issue by rahul4989** [Shiwsahaya/Secure-File-Storage-on-Cloud-Using-Hybrid-Cryptography#1]

**Comment by Shiwsahaya** [comment]
In this project, I used Java-8 and Java swing. If you have some basic knowledge about Java you can run it. You need to follow below step:-
1. Download Java-8 in your system.
2. Download NetBeans IDE to set up this project.
3. You need to add two jar files you can download from here
URL: https://jar-download.com/artifacts/org.apache.directory.studio/org.apache.commons.io/2.4/source-code
4. Add these jar files in the Libraries section.
5. I used hard-coded values for the file path. So make sure before a run you configure the file path according to your system.
6. You can start your project after starting the project you need to follow these steps.
a. First generate the key. It'll generate two private and public keys.
b. Choose the file which you want to encrypt your file will be encrypted.
d. For decrypting the file help of the decrypt option you can decrypt the file. It'll ask public key.

PS. As I said I used a hard-coded file path. Make sure you choose the correct path in code according to your system.

I hope it'll help you.
